---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
server:
  port: ${PORT:${SERVER_PORT:0}} 
---
spring:
  profiles: article
words: I,You,He,She,It
